/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetsSlugRouteImport } from './routes/projets.$slug'
import { Route as CertificatShortIdRouteImport } from './routes/certificat.$shortId'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedScoreRouteImport } from './routes/_authenticated/score'
import { Route as AuthenticatedProjetsRouteImport } from './routes/_authenticated/projets'
import { Route as AuthenticatedOrganisationRouteImport } from './routes/_authenticated/organisation'
import { Route as AuthenticatedFinancesRouteImport } from './routes/_authenticated/finances'
import { Route as AuthenticatedEvaluationRouteImport } from './routes/_authenticated/evaluation'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccompagnementRouteImport } from './routes/_authenticated/accompagnement'
import { Route as ApiPublicUnsubscribeRouteImport } from './routes/api/public/unsubscribe'
import { Route as AuthenticatedFinancesAnalyseRouteImport } from './routes/_authenticated/finances.analyse'
import { Route as ApiPublicHooksProcessEmailQueueRouteImport } from './routes/api/public/hooks/process-email-queue'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsSlugRoute = ProjetsSlugRouteImport.update({
  id: '/projets/$slug',
  path: '/projets/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatShortIdRoute = CertificatShortIdRouteImport.update({
  id: '/certificat/$shortId',
  path: '/certificat/$shortId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScoreRoute = AuthenticatedScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjetsRoute = AuthenticatedProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganisationRoute =
  AuthenticatedOrganisationRouteImport.update({
    id: '/organisation',
    path: '/organisation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinancesRoute = AuthenticatedFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEvaluationRoute = AuthenticatedEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccompagnementRoute =
  AuthenticatedAccompagnementRouteImport.update({
    id: '/accompagnement',
    path: '/accompagnement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicUnsubscribeRoute = ApiPublicUnsubscribeRouteImport.update({
  id: '/api/public/unsubscribe',
  path: '/api/public/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFinancesAnalyseRoute =
  AuthenticatedFinancesAnalyseRouteImport.update({
    id: '/analyse',
    path: '/analyse',
    getParentRoute: () => AuthenticatedFinancesRoute,
  } as any)
const ApiPublicHooksProcessEmailQueueRoute =
  ApiPublicHooksProcessEmailQueueRouteImport.update({
    id: '/api/public/hooks/process-email-queue',
    path: '/api/public/hooks/process-email-queue',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accompagnement': typeof AuthenticatedAccompagnementRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/evaluation': typeof AuthenticatedEvaluationRoute
  '/finances': typeof AuthenticatedFinancesRouteWithChildren
  '/organisation': typeof AuthenticatedOrganisationRoute
  '/projets': typeof AuthenticatedProjetsRoute
  '/score': typeof AuthenticatedScoreRoute
  '/support': typeof AuthenticatedSupportRoute
  '/certificat/$shortId': typeof CertificatShortIdRoute
  '/projets/$slug': typeof ProjetsSlugRoute
  '/finances/analyse': typeof AuthenticatedFinancesAnalyseRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/hooks/process-email-queue': typeof ApiPublicHooksProcessEmailQueueRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/accompagnement': typeof AuthenticatedAccompagnementRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/evaluation': typeof AuthenticatedEvaluationRoute
  '/finances': typeof AuthenticatedFinancesRouteWithChildren
  '/organisation': typeof AuthenticatedOrganisationRoute
  '/projets': typeof AuthenticatedProjetsRoute
  '/score': typeof AuthenticatedScoreRoute
  '/support': typeof AuthenticatedSupportRoute
  '/certificat/$shortId': typeof CertificatShortIdRoute
  '/projets/$slug': typeof ProjetsSlugRoute
  '/finances/analyse': typeof AuthenticatedFinancesAnalyseRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/hooks/process-email-queue': typeof ApiPublicHooksProcessEmailQueueRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/accompagnement': typeof AuthenticatedAccompagnementRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/evaluation': typeof AuthenticatedEvaluationRoute
  '/_authenticated/finances': typeof AuthenticatedFinancesRouteWithChildren
  '/_authenticated/organisation': typeof AuthenticatedOrganisationRoute
  '/_authenticated/projets': typeof AuthenticatedProjetsRoute
  '/_authenticated/score': typeof AuthenticatedScoreRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/certificat/$shortId': typeof CertificatShortIdRoute
  '/projets/$slug': typeof ProjetsSlugRoute
  '/_authenticated/finances/analyse': typeof AuthenticatedFinancesAnalyseRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
  '/api/public/hooks/process-email-queue': typeof ApiPublicHooksProcessEmailQueueRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/accompagnement'
    | '/dashboard'
    | '/documents'
    | '/evaluation'
    | '/finances'
    | '/organisation'
    | '/projets'
    | '/score'
    | '/support'
    | '/certificat/$shortId'
    | '/projets/$slug'
    | '/finances/analyse'
    | '/api/public/unsubscribe'
    | '/api/public/hooks/process-email-queue'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/accompagnement'
    | '/dashboard'
    | '/documents'
    | '/evaluation'
    | '/finances'
    | '/organisation'
    | '/projets'
    | '/score'
    | '/support'
    | '/certificat/$shortId'
    | '/projets/$slug'
    | '/finances/analyse'
    | '/api/public/unsubscribe'
    | '/api/public/hooks/process-email-queue'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/accompagnement'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/evaluation'
    | '/_authenticated/finances'
    | '/_authenticated/organisation'
    | '/_authenticated/projets'
    | '/_authenticated/score'
    | '/_authenticated/support'
    | '/certificat/$shortId'
    | '/projets/$slug'
    | '/_authenticated/finances/analyse'
    | '/api/public/unsubscribe'
    | '/api/public/hooks/process-email-queue'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CertificatShortIdRoute: typeof CertificatShortIdRoute
  ProjetsSlugRoute: typeof ProjetsSlugRoute
  ApiPublicUnsubscribeRoute: typeof ApiPublicUnsubscribeRoute
  ApiPublicHooksProcessEmailQueueRoute: typeof ApiPublicHooksProcessEmailQueueRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets/$slug': {
      id: '/projets/$slug'
      path: '/projets/$slug'
      fullPath: '/projets/$slug'
      preLoaderRoute: typeof ProjetsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificat/$shortId': {
      id: '/certificat/$shortId'
      path: '/certificat/$shortId'
      fullPath: '/certificat/$shortId'
      preLoaderRoute: typeof CertificatShortIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/score': {
      id: '/_authenticated/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof AuthenticatedScoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projets': {
      id: '/_authenticated/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof AuthenticatedProjetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/organisation': {
      id: '/_authenticated/organisation'
      path: '/organisation'
      fullPath: '/organisation'
      preLoaderRoute: typeof AuthenticatedOrganisationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finances': {
      id: '/_authenticated/finances'
      path: '/finances'
      fullPath: '/finances'
      preLoaderRoute: typeof AuthenticatedFinancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/evaluation': {
      id: '/_authenticated/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof AuthenticatedEvaluationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/accompagnement': {
      id: '/_authenticated/accompagnement'
      path: '/accompagnement'
      fullPath: '/accompagnement'
      preLoaderRoute: typeof AuthenticatedAccompagnementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/unsubscribe': {
      id: '/api/public/unsubscribe'
      path: '/api/public/unsubscribe'
      fullPath: '/api/public/unsubscribe'
      preLoaderRoute: typeof ApiPublicUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/finances/analyse': {
      id: '/_authenticated/finances/analyse'
      path: '/analyse'
      fullPath: '/finances/analyse'
      preLoaderRoute: typeof AuthenticatedFinancesAnalyseRouteImport
      parentRoute: typeof AuthenticatedFinancesRoute
    }
    '/api/public/hooks/process-email-queue': {
      id: '/api/public/hooks/process-email-queue'
      path: '/api/public/hooks/process-email-queue'
      fullPath: '/api/public/hooks/process-email-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessEmailQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedFinancesRouteChildren {
  AuthenticatedFinancesAnalyseRoute: typeof AuthenticatedFinancesAnalyseRoute
}

const AuthenticatedFinancesRouteChildren: AuthenticatedFinancesRouteChildren = {
  AuthenticatedFinancesAnalyseRoute: AuthenticatedFinancesAnalyseRoute,
}

const AuthenticatedFinancesRouteWithChildren =
  AuthenticatedFinancesRoute._addFileChildren(
    AuthenticatedFinancesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccompagnementRoute: typeof AuthenticatedAccompagnementRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedEvaluationRoute: typeof AuthenticatedEvaluationRoute
  AuthenticatedFinancesRoute: typeof AuthenticatedFinancesRouteWithChildren
  AuthenticatedOrganisationRoute: typeof AuthenticatedOrganisationRoute
  AuthenticatedProjetsRoute: typeof AuthenticatedProjetsRoute
  AuthenticatedScoreRoute: typeof AuthenticatedScoreRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccompagnementRoute: AuthenticatedAccompagnementRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedEvaluationRoute: AuthenticatedEvaluationRoute,
  AuthenticatedFinancesRoute: AuthenticatedFinancesRouteWithChildren,
  AuthenticatedOrganisationRoute: AuthenticatedOrganisationRoute,
  AuthenticatedProjetsRoute: AuthenticatedProjetsRoute,
  AuthenticatedScoreRoute: AuthenticatedScoreRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CertificatShortIdRoute: CertificatShortIdRoute,
  ProjetsSlugRoute: ProjetsSlugRoute,
  ApiPublicUnsubscribeRoute: ApiPublicUnsubscribeRoute,
  ApiPublicHooksProcessEmailQueueRoute: ApiPublicHooksProcessEmailQueueRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
